using System.ComponentModel.DataAnnotations;

namespace sacpapi.Models
{
    public class APGroup
    {
        [Key]
        public int Id { get; set; } = 0;
        public string? province { get; set; }
        public string? district { get; set; }
        public string? ward { get; set; }
        public string? nameapg { get; set; }
        public string? point { get; set; }
        public string? namevil { get; set; }
        public int yearest { get; set; }
        public int nointeger { get; set; }
        public int females { get; set; }
        public int males { get; set; }
        public int youth { get; set; }
        public int youth_001 { get; set; }
        public string? subsector { get; set; }
        public string? valuechain { get; set; }
        public string? enumerator { get; set; }
        public string? contact { get; set; }
        public string? chair { get; set; }
        public string? sex { get; set; }
        public int age { get; set; }
        public string? category { get; set; }
        public string? vice { get; set; }
        public string? sex_001 { get; set; }
        public int age_001 { get; set; }
        public string? category_001 { get; set; }
        public string? sec { get; set; }
        public string? sex_002 { get; set; }
        public int age_002 { get; set; }
        public string? category_002 { get; set; }
        public string? ward_001 { get; set; }
        public string? sex_003 { get; set; }
        public int age_003 { get; set; }
        public string? category_003 { get; set; }
        public string? treas { get; set; }
        public string? sex_004 { get; set; }
        public int age_004 { get; set; }
        public string? category_004 { get; set; }
        public string? group { get; set; }
        public string? sex_005 { get; set; }
        public int age_005 { get; set; }
        public string? category_005 { get; set; }
        public string? group_001 { get; set; }
        public string? sex_006 { get; set; }
        public int age_006 { get; set; }
        public string? category_006 { get; set; }
        public string? group_002 { get; set; }
        public string? sex_007 { get; set; }
        public int age_007 { get; set; }
        public string? category_007 { get; set; }
        public string? group_003 { get; set; }
        public string? sex_008 { get; set; }
        public int age_008 { get; set; }
        public string? category_008 { get; set; }
        public string? group_004 { get; set; }
        public string? sex_009 { get; set; }
        public int age_009 { get; set; }
        public string? category_009 { get; set; }
        public string? group_005 { get; set; }
        public string? sex_010 { get; set; }
        public int age_010 { get; set; }
        public string? category_010 { get; set; }
        public string? group_006 { get; set; }
        public string? sex_011 { get; set; }
        public int age_011 { get; set; }
        public string? category_011 { get; set; }
        public string? group_007 { get; set; }
        public string? sex_012 { get; set; }
        public int age_012 { get; set; }
        public string? category_012 { get; set; }
        public string? group_008 { get; set; }
        public string? sex_013 { get; set; }
        public int age_013 { get; set; }
        public string? category_013 { get; set; }
        public string? group_009 { get; set; }
        public string? sex_014 { get; set; }
        public int age_014 { get; set; }
        public string? category_014 { get; set; }
        public string? group_010 { get; set; }
        public string? sex_015 { get; set; }
        public int age_015 { get; set; }
        public string? category_015 { get; set; }
        public string? group_011 { get; set; }
        public string? sex_016 { get; set; }
        public int age_016 { get; set; }
        public string? category_016 { get; set; }
        public string? group_012 { get; set; }
        public string? sex_017 { get; set; }
        public int age_017 { get; set; }
        public string? category_017 { get; set; }
        public string? group_013 { get; set; }
        public string? sex_018 { get; set; }
        public int age_018 { get; set; }
        public string? category_018 { get; set; }
        public string? group_014 { get; set; }
        public string? sex_019 { get; set; }
        public int age_019 { get; set; }
        public string? category_019 { get; set; }
        public string? group_015 { get; set; }
        public string? sex_020 { get; set; }
        public int age_020 { get; set; }
        public string? category_020 { get; set; }
        public string? group_016 { get; set; }
        public string? sex_021 { get; set; }
        public int age_021 { get; set; }
        public string? category_021 { get; set; }
        public string? group_017 { get; set; }
        public string? sex_022 { get; set; }
        public int age_022 { get; set; }
        public string? category_022 { get; set; }
        public string? group_018 { get; set; }
        public string? sex_023 { get; set; }
        public int age_023 { get; set; }
        public string? category_023 { get; set; }
        public string? group_019 { get; set; }
        public string? sex_024 { get; set; }
        public int age_024 { get; set; }
        public string? category_024 { get; set; }
        public string? group_020 { get; set; }
        public string? sex_025 { get; set; }
        public int age_025 { get; set; }
        public string? category_025 { get; set; }
        public string? group_021 { get; set; }
        public string? sex_026 { get; set; }
        public int age_026 { get; set; }
        public string? category_026 { get; set; }
        public string? group_022 { get; set; }
        public string? sex_027 { get; set; }
        public int age_027 { get; set; }
        public string? category_027 { get; set; }
        public string? group_023 { get; set; }
        public string? sex_028 { get; set; }
        public int age_028 { get; set; }
        public string? category_028 { get; set; }
        public string? group_024 { get; set; }
        public string? sex_029 { get; set; }
        public int age_029 { get; set; }
        public string? category_029 { get; set; }
        public string? group_025 { get; set; }
        public string? sex_030 { get; set; }
        public int age_030 { get; set; }
        public string? category_030 { get; set; }
        public string? group_026 { get; set; }
        public string? sex_031 { get; set; }
        public int age_031 { get; set; }
        public string? category_031 { get; set; }
        public string? group_027 { get; set; }
        public string? sex_032 { get; set; }
        public int age_032 { get; set; }
        public string? category_032 { get; set; }
        public string? group_028 { get; set; }
        public string? sex_033 { get; set; }
        public int age_033 { get; set; }
        public string? category_033 { get; set; }
        public string? group_029 { get; set; }
        public string? sex_034 { get; set; }
        public int age_034 { get; set; }
        public string? category_034 { get; set; }
        public int _id { get; set; }
        public string? _uuid { get; set; }
        public DateTime _submission_time { get; set; }
        public string? _status { get; set; }
        public string? _submitted_by { get; set; }
        public string? __version__ { get; set; }

    }
}

