using System.ComponentModel.DataAnnotations;

namespace sacpapi.Models
{
    public class FocusGroupDiscussion
    {
        [Key]
        //public int mId { get; set; } = 0;
        public int Id { get; set; } = 0;
        public DateTime today { get; set; }
        public string? point { get; set; }
        public string? enumerator { get; set; }
        public string? province { get; set; }
        public string? district { get; set; }
        public string? ward { get; set; }
        public string? village { get; set; }
        public string? Name_of_the_Village_2 { get; set; }
        public string? Name_of_the_Village_3 { get; set; }
        public string? Name_of_the_Village_4 { get; set; }
        public string? Name_of_the_Village_5 { get; set; }
        public string? Name_of_the_Village_6 { get; set; }
        public string? Name_of_the_Village_7 { get; set; }
        public string? Name_of_the_Village_8 { get; set; }
        public string? Name_of_the_Village_9 { get; set; }
        public string? Name_of_the_Village_10 { get; set; }
        public int noparticipants { get; set; }
        public int youth { get; set; }
        public int youth_001 { get; set; }
        public int females { get; set; }
        public int males { get; set; }
        public int disability { get; set; }
        public string? intro { get; set; }
        public string? gen { get; set; }
        public string? smallirr { get; set; }
        public string? Size_of_irrigation_scheme_in_village_1 { get; set; }
        public string? smallirr_009 { get; set; }
        public string? smallirr_008 { get; set; }
        public string? smallirr_007 { get; set; }
        public string? smallirr_006 { get; set; }
        public string? smallirr_005 { get; set; }
        public string? smallirr_004 { get; set; }
        public string? smallirr_003 { get; set; }
        public string? smallirr_002 { get; set; }
        public string? smallirr_001 { get; set; }
        public string? numberirr { get; set; }
        public string? nameirr1 { get; set; }
        public string? nameirr2 { get; set; }
        public string? nameirr3 { get; set; }
        public string? sizeirr1 { get; set; }
        public string? sizeirr2 { get; set; }
        public string? sizeirr3 { get; set; }
        public string? systemused { get; set; }
        public string? systemused_piped_surface_open_channel_flow__pumped_ { get; set; }
        public string? systemused_overhead { get; set; }
        public string? systemused_localised { get; set; }
        public string? systemused_na { get; set; }
        public string? systemused_other { get; set; }
        public string? otherirr1 { get; set; }
        public string? systemused_001 { get; set; }
        public string? systemused_001_piped_surface_open_channel_flow__pumped_ { get; set; }
        public string? systemused_001_overhead { get; set; }
        public string? systemused_001_localised { get; set; }
        public string? systemused_001_na { get; set; }
        public string? systemused_001_other { get; set; }
        public string? otherirr2 { get; set; }
        public string? systemused_002 { get; set; }
        public string? systemused_002_piped_surface_open_channel_flow__pumped_ { get; set; }
        public string? systemused_002_overhead { get; set; }
        public string? systemused_002_localised { get; set; }
        public string? systemused_002_na { get; set; }
        public string? systemused_002_other { get; set; }
        public string? otherirr3 { get; set; }
        public string? challengs { get; set; }
        public string? challengs_001 { get; set; }
        public string? challengs_002 { get; set; }
        public string? whatchale { get; set; }
        public string? whatchale_government { get; set; }
        public string? whatchale_accessinpu { get; set; }
        public string? whatchale_mktaccess { get; set; }
        public string? whatchale_irrinfra { get; set; }
        public string? whatchale_wateravail { get; set; }
        public string? whatchale_n_a { get; set; }
        public string? whatchale_otherchale { get; set; }
        public string? other1 { get; set; }
        public string? whatchale_001 { get; set; }
        public string? whatchale_001_government { get; set; }
        public string? whatchale_001_accessinpu { get; set; }
        public string? whatchale_001_mktaccess { get; set; }
        public string? whatchale_001_irrinfra { get; set; }
        public string? whatchale_001_wateravail { get; set; }
        public string? whatchale_001_n_a { get; set; }
        public string? whatchale_001_otherchale { get; set; }
        public string? other2 { get; set; }
        public string? whatchale_002 { get; set; }
        public string? whatchale_002_government { get; set; }
        public string? whatchale_002_accessinpu { get; set; }
        public string? whatchale_002_mktaccess { get; set; }
        public string? whatchale_002_irrinfra { get; set; }
        public string? whatchale_002_wateravail { get; set; }
        public string? whatchale_002_n_a { get; set; }
        public string? whatchale_002_otherchale { get; set; }
        public string? other3 { get; set; }
        public string? feeder { get; set; }
        public string? road { get; set; }
        public string? road_003 { get; set; }
        public string? road_002 { get; set; }
        public string? points { get; set; }
        public string? domuse { get; set; }
        public string? domuse_taps { get; set; }
        public string? domuse_borehole { get; set; }
        public string? domuse_wells { get; set; }
        public string? domuse_river { get; set; }
        public string? domuse_otherdomeuse { get; set; }
        public string? otherdomuse { get; set; }
        public string? time { get; set; }
        public string? rainfall { get; set; }
        public string? reliability { get; set; }
        public string? sani { get; set; }
        public string? ablution { get; set; }
        public string? ablution_002 { get; set; }
        public string? ablution_001 { get; set; }
        public string? ablution_001_007 { get; set; }
        public string? ablution_001_006 { get; set; }
        public string? ablution_001_005 { get; set; }
        public string? ablution_001_004 { get; set; }
        public string? ablution_001_003 { get; set; }
        public string? ablution_001_002 { get; set; }
        public string? ablution_001_001 { get; set; }
        public string? otherablution { get; set; }
        public string? env { get; set; }
        public string? environ { get; set; }
        public string? issues_007 { get; set; }
        public string? issues_007_gullies { get; set; }
        public string? issues_007_minepit { get; set; }
        public string? issues_007_otherissues { get; set; }
        public string? environ_009 { get; set; }
        public string? issues { get; set; }
        public string? issues_gullies { get; set; }
        public string? issues_minepit { get; set; }
        public string? issues_otherissues { get; set; }
        public string? environ_008 { get; set; }
        public string? issues_003 { get; set; }
        public string? issues_003_gullies { get; set; }
        public string? issues_003_minepit { get; set; }
        public string? issues_003_otherissues { get; set; }
        public string? environ_007 { get; set; }
        public string? issues_009 { get; set; }
        public string? issues_009_gullies { get; set; }
        public string? issues_009_minepit { get; set; }
        public string? issues_009_otherissues { get; set; }
        public string? environ_006 { get; set; }
        public string? issues_002 { get; set; }
        public string? issues_002_gullies { get; set; }
        public string? issues_002_minepit { get; set; }
        public string? issues_002_otherissues { get; set; }
        public string? environ_005 { get; set; }
        public string? issues_008 { get; set; }
        public string? issues_008_gullies { get; set; }
        public string? issues_008_minepit { get; set; }
        public string? issues_008_otherissues { get; set; }
        public string? environ_004 { get; set; }
        public string? issues_006 { get; set; }
        public string? issues_006_gullies { get; set; }
        public string? issues_006_minepit { get; set; }
        public string? issues_006_otherissues { get; set; }
        public string? environ_003 { get; set; }
        public string? issues_005 { get; set; }
        public string? issues_005_gullies { get; set; }
        public string? issues_005_minepit { get; set; }
        public string? issues_005_otherissues { get; set; }
        public string? environ_002 { get; set; }
        public string? issues_004 { get; set; }
        public string? issues_004_gullies { get; set; }
        public string? issues_004_minepit { get; set; }
        public string? issues_004_otherissues { get; set; }
        public string? environ_001 { get; set; }
        public string? issues_001 { get; set; }
        public string? issues_001_gullies { get; set; }
        public string? issues_001_minepit { get; set; }
        public string? issues_001_otherissues { get; set; }
        public string? otherissues { get; set; }
        public string? ngo { get; set; }
        public string? conl { get; set; }
        public string? This_note_can_be_read_out_loud { get; set; }
        public string? Youth_group { get; set; }
        public string? redressing { get; set; }
        public string? rankneeds { get; set; }
        public string? suggestedneeds_001 { get; set; }
        public string? Female_group { get; set; }
        public string? redressing_001 { get; set; }
        public string? rankneeds_001 { get; set; }
        public string? suggestedneeds { get; set; }
        public string? Male_Group { get; set; }
        public string? redressing_001_002 { get; set; }
        public string? rankneeds_002 { get; set; }
        public string? suggestedneeds_001_001 { get; set; }
        public string? road_001 { get; set; }
        public int _id { get; set; }
        public string? _uuid { get; set; }
        public DateTime _submission_time { get; set; }
        public string? _status { get; set; }
        public string? _submitted_by { get; set; }
    }
}
